Devsite 1192: Icons with Links formatting
adobe/adobe-io-website pull request #141
Opened 2024-06-17 22:56 UTC by Elisha-Edme

Icons only displayed small if followed by a link. 

## Description

I made an if statement so that that even text gets added to the product link container div. I also enwrapped non-links in an paragraph tag with class "icon-text", so that there would be some space between the icon and the text next to it.

## Related Issue

[Jira Ticket](https://jira.corp.adobe.com/browse/DEVSITE-1192)
## Motivation and Context
Icons should be able to have non-linked text associated with them without becoming huge.

## How Has This Been Tested?
I just modified the code and checked if the DOM was intact. I looked at it on localhost and the images came out to the right size.

https://docs.google.com/document/d/1RphfPEBfnnFrOAm1nPrmdks8VTjdQRtPTgTwuVsL0Jc/edit
^This is Erin's original google doc that caused the errors
[This is my copy](https://docs.google.com/document/d/1JXEvSKLnYuSaBdunL_n7VXcksab6oFM5QGotJyIw6mQ/edit)
## Screenshots (if appropriate):
Before:
![image](https://github.com/adobe/adobe-io-website/assets/90655196/720f1d5c-2ad6-4a24-9fb7-61f22405a530)
<img width="1194" alt="image" src="https://github.com/adobe/adobe-io-website/assets/90655196/10a69464-65b2-4a29-b242-c72834c495df">
<img width="1194" alt="image" src="https://github.com/adobe/adobe-io-website/assets/90655196/f4645293-6582-4faa-b661-cdd556bfef2b">

After:
<img width="1248" alt="image" src="https://github.com/adobe/adobe-io-website/assets/90655196/b6914ac1-1156-4180-afe0-4e3256c90890">
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-06-19 16:15 UTC, Elisha-Edme commented
It looks like this also solves [this Jira Ticket](https://jira.corp.adobe.com/browse/DEVSITE-1172). You can test using [this link](https://devsite-1192--adobe-io-website--adobe.hlx.page/test/Eli/1172).

2024-06-20 18:05 UTC, timkim commented
I think we need to make sure we're not breaking other columns formats:
https://main--adobe-io-website--adobe.hlx.page/#heading-3-is-the-size-with-bold

https://devsite-1192--adobe-io-website--adobe.hlx.page/#heading-3-is-the-size-with-bold

I can see the icons are misaligned here.

2024-06-20 18:05 UTC, timkim requested changes
See comment I put in the pr

2024-07-19 21:07 UTC, timkim approved these changes

2024-07-19 21:34 UTC, merged