CodeBlock
adobe/adobe-io-website pull request #206
Opened 2024-08-08 05:10 UTC by melissag-ensemble

## Description

EDS equivalent of Gatsby [CodeBlock](https://github.com/adobe/aio-theme/blob/main/packages/gatsby-theme-aio/src/components/CodeBlock/index.js#L19) block

## Related Issue

https://jira.corp.adobe.com/browse/DEVSITE-1079

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-08-08 23:11 UTC, timkim commented
This looks great @melissag-ensemble! However, we don't need all of the prism grammars...
I'm thinking just:
- bash
- c
- cpp
- csharp
- css-extras
- css
- git
- go
- graphql
- http
- java
- javadoc
- javascript
- jsdoc
- json
- json5
- jsx
- less
- markdown
- objectivec
- php
- python
- regex
- rest
- sass
- sql
- typescript
- xml
- yaml

And maybe some others if they make sense. We can always add more when users request.

2024-08-08 23:12 UTC, timkim requested changes
See comment on what we should include with prism grammars...

2024-08-09 16:37 UTC, melissag-ensemble commented
I had to bring back 'clike' because for some reason, javascript wouldn't syntax highlight without it

2024-08-09 20:37 UTC, timkim approved these changes

2024-08-09 20:37 UTC, merged