Contributors spectrum less
adobe/adobe-io-website pull request #214
Opened 2024-08-16 13:27 UTC by BaskarMitrah

## Description

Contributors component 

## Related Issue

This block is created with the static content but needs to update the content with the GitHub details

## Motivation and Context

## How Has This Been Tested?

https://contributors-spectrum-less--adobe-io-website--adobe.hlx.page/test/contributors

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-08-16 13:46 UTC, melissag-ensemble approved these changes

2024-08-16 18:05 UTC, timkim requested changes
Oh it's looking good but I'm noticing a border on the nav
<img width="233" alt="Screenshot 2024-08-16 at 11 03 59 AM" src="https://github.com/user-attachments/assets/66bedbc4-125c-4d56-910b-c12437970357">

2024-08-19 15:44 UTC, BaskarMitrah commented
> Oh it's looking good but I'm noticing a border on the nav <img alt="Screenshot 2024-08-16 at 11 03 59 AM" width="233" src="https://private-user-images.githubusercontent.com/57922/358671405-66bedbc4-125c-4d56-910b-c12437970357.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODI1NDYsIm5iZiI6MTcyNDA4MjI0NiwicGF0aCI6Ii81NzkyMi8zNTg2NzE0MDUtNjZiZWRiYzQtMTI1Yy00ZDU2LTkxMGItYzEyNDM3OTcwMzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE1NDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NGRjYWU3NDdlMTJhZDhmOWE3NGY1YTZmNDMzMTk5NmM2YTBiNjJhMTQ1YWM1ZTg0YTU1ZTAzMzkxNzdjMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YE87JRQ3cRkSqYB-7GhEtiE9335fC55c7iHUKQBIrxs">

I've fixed the issue

2024-08-23 20:30 UTC, timkim approved these changes

2024-08-23 20:30 UTC, merged