Devsite 1240 onthispage spectrum less
adobe/adobe-io-website pull request #217
Opened 2024-08-20 13:50 UTC by manimitrah

## Description

EDS- Convert OnThisPage

## Related Issue

## Motivation and Context

## How Has This Been Tested?

https://devsite-1240-onthispage-spectrum-less--adobe-io-website--adobe.hlx.page/test/documentation

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-08-20 14:09 UTC, melissag-ensemble commented on hlx_statics/blocks/onthispage/onthispage.js
> + * decorates the title
copy paste error?

2024-08-20 14:17 UTC, melissag-ensemble requested changes
sub links should be indented like in https://developer.adobe.com/commerce/webapi/rest/b2b/company-users/

2024-08-21 14:43 UTC, melissag-ensemble approved these changes

2024-08-23 20:33 UTC, timkim approved these changes

2024-08-23 20:34 UTC, merged