update files for sidekick
adobe/adobe-io-website pull request #99
Opened 2023-09-21 23:10 UTC by louisachu

update files for sidekick

## Description
update files for sidekick

## Related Issue
devsite-864

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-09-21 23:21 UTC, dmitrymatio approved these changes
Needed for library plugin lgtm

2023-09-21 23:22 UTC, dmitrymatio requested changes
can this be merged into stage first?

2023-09-21 23:39 UTC, dmitrymatio commented
> can this be merged into stage first?
Louisa: "it’s actually in stage already but I’m talking to the franklin library creator and he said these files need to be in main in order to see the library button, that’s why I’m just trying to merge these two files and leave what’s behind in stage."

2023-09-21 23:39 UTC, dmitrymatio approved these changes

2023-09-22 00:00 UTC, dylandepass requested changes

2023-09-22 00:00 UTC, dylandepass commented on tools/sidekick/config.json
> +  "project": "adobe-io",
add `"host":  {your production host}"

as per https://www.hlx.live/docs/sidekick#customizing-the-sidekick

2023-09-22 00:09 UTC, dylandepass requested changes

2023-09-22 00:09 UTC, dylandepass commented on tools/sidekick/library.json
> +  "host": "https://www.hlx.live/docs/sidekick#customizing-the-sidekick",
You had it right before.. This needs to be your production hostname i.e developer.adobe.com?

2023-09-22 00:17 UTC, dylandepass approved these changes

2023-09-22 00:20 UTC, dmitrymatio commented
@dylandepass Thanks for the help!

2023-09-22 00:23 UTC, dylandepass commented
@dmitrymatio Happy to help. Tell Dawn I say hi 👋🏻

2023-10-19 23:09 UTC, closed without merging